### ISSUE TITLE
Button disappeared, comments reappeared

### ISSUE THREAD

**Issue by paleguy** [hadalin/chrome-hidefedora#50] opened 2015-03-07 15:46 UTC
Suddenly i don't see those "meow meow" comments anymore but the reddit comments have returned. i also don't see the button "hide fedora" anymore.. chrome says it's installed and active.. pls help, it's like if my freedom was stolen again.

**Comment by hadalin** [comment] 2015-03-07 17:10
@paleguy what OS and Chrome version are you using?

**Comment by hadalin** [comment] 2015-03-07 17:11
This is duplicate of https://github.com/hadalin/chrome-hidefedora/issues/49

**Closed** 2015-03-07 17:11 UTC
Labels: duplicate

**Comment by hadalin** [comment] 2015-03-08 09:24
@paleguy Log back in to Chrome or install Hide Fedora while logged out.
