### ISSUE TITLE
Hide Fedora stopped working.

### ISSUE THREAD

**Issue by Umaroth** [hadalin/chrome-hidefedora#51] opened 2015-03-07 18:31 UTC
A couple days ago the extension simply stopped working entirely. I didn't add any new extensions. I tried disabling and reenabling the extension and I tried uninstalling and reinstalling it and it still doesn't work.

My extensions page says it's installed, enabled and working properly but It doesn't block any banned profiles and there is no Hide Fedora button under comments.

**Comment by Fogest** [comment] 2015-03-07 18:32
What version of Chrome are you using? What operating system are you using? Does it work in other browsers?

**Comment by Umaroth** [comment] 2015-03-07 18:38
Chrome Version 40.0.2214.115 m --- Hide Fedora version 1.7.2

Windows 8

Tried in Firefox Version 33.0.2 (HF version 1.7.1) and it works in there but not in Chrome.

When I went to check Chromes version it started updating so maybe it'll work after the update, I'll post back.

**Comment by Umaroth** [comment] 2015-03-07 18:39
Nope, still doesn't work after updating to Chrome Version 41.0.2272.76 m, which is up to date.

**Comment by Fogest** [comment] 2015-03-07 18:39
Okay thanks for the information. Check out issue #49 where others are reporting the same issues.

**Comment by hadalin** [comment] 2015-03-07 18:43
Duplicate of https://github.com/hadalin/chrome-hidefedora/issues/49

**Closed by hadalin** 2015-03-07 18:43 UTC
Labels: duplicate
